package page.authentication;

import page.admin.DashboardAdmin;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import javax.swing.JOptionPane;
import page.user.DashboardUser;

public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }
    
    static String status, type;
    
    public static int loginAcc(String username, String password){
        dbConnector connector = new dbConnector();
        
        try{
            String query = "SELECT * FROM dashboard_members WHERE member_name = '"+username+"'";
            ResultSet resultSet = connector.getData(query);
            if(resultSet.next()){
                
               
                    String hashedPass = resultSet.getString("member_password");
                    String rehashedPass = passwordHasher.hashPassword(password);
                    
                    System.out.println(""+hashedPass);
                    System.out.println(""+rehashedPass);
                    
                    if(hashedPass.equals(rehashedPass)){
                        status = resultSet.getString("member_status");
                        type = resultSet.getString("member_position");

                        Session sess = Session.getInstance();
                        sess.setId(resultSet.getInt("member_id"));
                        sess.setName(resultSet.getString("member_name"));
                        sess.setEmail(resultSet.getString("member_email"));
                        sess.setType(resultSet.getString("member_position"));
                        sess.setStatus(resultSet.getString("member_status"));

                        System.out.println(""+sess.getId());
                        return 1;
                    }
                    else{
                        return 0;
                    }
                }
            else{
                return 0;
            }
        }catch(SQLException | NoSuchAlgorithmException ex){
               System.out.println(""+ex);
                   
            return 0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerContainer = new javax.swing.JPanel();
        register_imageContainer = new javax.swing.JPanel();
        register_formContainer = new javax.swing.JPanel();
        login_nameLabel = new javax.swing.JLabel();
        login_nameField = new javax.swing.JTextField();
        login_passwordLabel = new javax.swing.JLabel();
        login_passwordField = new javax.swing.JPasswordField();
        login_exitButton = new javax.swing.JPanel();
        login_exitLabel = new javax.swing.JLabel();
        login_loginButton = new javax.swing.JPanel();
        login_registerLabel = new javax.swing.JLabel();
        login_createLabel = new javax.swing.JLabel();
        login_resetLabel = new javax.swing.JLabel();
        register_headerContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        registerContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_imageContainer.setBackground(new java.awt.Color(132, 71, 71));
        register_imageContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        registerContainer.add(register_imageContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 340));

        register_formContainer.setBackground(new java.awt.Color(183, 71, 52));
        register_formContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        login_nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_nameLabel.setText("Name:");
        register_formContainer.add(login_nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        login_nameField.setBackground(new java.awt.Color(192, 132, 139));
        login_nameField.setForeground(new java.awt.Color(255, 255, 255));
        register_formContainer.add(login_nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        login_passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        login_passwordLabel.setText("Password:");
        register_formContainer.add(login_passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        login_passwordField.setBackground(new java.awt.Color(192, 132, 139));
        login_passwordField.setForeground(new java.awt.Color(255, 255, 255));
        register_formContainer.add(login_passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 30));

        login_exitButton.setBackground(new java.awt.Color(132, 72, 79));
        login_exitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        login_exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_exitButtonMouseExited(evt);
            }
        });
        login_exitButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_exitLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        login_exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_exitLabel.setText("Exit");
        login_exitButton.add(login_exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        register_formContainer.add(login_exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 20));

        login_loginButton.setBackground(new java.awt.Color(132, 72, 79));
        login_loginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        login_loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_loginButtonMouseExited(evt);
            }
        });
        login_loginButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_registerLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        login_registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_registerLabel.setText("Login");
        login_loginButton.add(login_registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        register_formContainer.add(login_loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 20));

        login_createLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_createLabel.setForeground(new java.awt.Color(255, 255, 255));
        login_createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_createLabel.setText("New User? Create Account");
        login_createLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_createLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_createLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_createLabelMouseExited(evt);
            }
        });
        register_formContainer.add(login_createLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 20));

        login_resetLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_resetLabel.setForeground(new java.awt.Color(255, 255, 255));
        login_resetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_resetLabel.setText("Forgot Password?");
        login_resetLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_resetLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_resetLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_resetLabelMouseExited(evt);
            }
        });
        register_formContainer.add(login_resetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 284, 170, 20));

        registerContainer.add(register_formContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 190, 340));

        register_headerContainer.setBackground(new java.awt.Color(121, 51, 65));
        register_headerContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        register_headerContainer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 5, 60, 20));

        registerContainer.add(register_headerContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_login_exitButtonMouseClicked

    private void login_loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_loginButtonMouseClicked
      
        if(loginAcc(login_nameField.getText(), login_passwordField.getText()) == 1){
        if(!status.equals("Active")){
            JOptionPane.showMessageDialog(null, "Inactive account, contact the admin!");
            }
            else{
                switch (type) {
                    case "Admin":
                        JOptionPane.showMessageDialog(null, "Login Successfully!");
                        DashboardAdmin adminPage = new DashboardAdmin();
                        adminPage.setVisible(true);
                        this.dispose();
                        break;
                    case "User":
                        JOptionPane.showMessageDialog(null, "Login Successfully!");
                        DashboardUser userPage = new DashboardUser();
                        userPage.setVisible(true);
                        this.dispose();
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "No account type found, contact the admin!");
                        break;
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid Account!");
        }
        
    }//GEN-LAST:event_login_loginButtonMouseClicked

    private void login_exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_exitButtonMouseEntered
        login_exitButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_login_exitButtonMouseEntered

    private void login_exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_exitButtonMouseExited
        login_exitButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_login_exitButtonMouseExited

    private void login_loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_loginButtonMouseEntered
        login_loginButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_login_loginButtonMouseEntered

    private void login_loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_loginButtonMouseExited
        login_loginButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_login_loginButtonMouseExited

    private void login_createLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_createLabelMouseEntered
        login_createLabel.setForeground(new Color(192, 132, 139));
    }//GEN-LAST:event_login_createLabelMouseEntered

    private void login_createLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_createLabelMouseExited
        login_createLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_login_createLabelMouseExited

    private void login_createLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_createLabelMouseClicked
        RegisterForm register = new RegisterForm();
        
        register.setVisible(true);
        dispose();
    }//GEN-LAST:event_login_createLabelMouseClicked

    private void login_resetLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_resetLabelMouseClicked
        RecoveryForm reset = new RecoveryForm();
        reset.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_login_resetLabelMouseClicked

    private void login_resetLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_resetLabelMouseEntered
        login_resetLabel.setForeground(new Color(192, 132, 139));
    }//GEN-LAST:event_login_resetLabelMouseEntered

    private void login_resetLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_resetLabelMouseExited
        login_resetLabel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_login_resetLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel login_createLabel;
    private javax.swing.JPanel login_exitButton;
    private javax.swing.JLabel login_exitLabel;
    private javax.swing.JPanel login_loginButton;
    private javax.swing.JTextField login_nameField;
    private javax.swing.JLabel login_nameLabel;
    private javax.swing.JPasswordField login_passwordField;
    private javax.swing.JLabel login_passwordLabel;
    private javax.swing.JLabel login_registerLabel;
    private javax.swing.JLabel login_resetLabel;
    private javax.swing.JPanel registerContainer;
    private javax.swing.JPanel register_formContainer;
    private javax.swing.JPanel register_headerContainer;
    private javax.swing.JPanel register_imageContainer;
    // End of variables declaration//GEN-END:variables
}
