/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package page.authentication;

import java.awt.Color;

/**
 *
 * @author champ
 */
public class RecoveryForm extends javax.swing.JFrame {

    /**
     * Creates new form RecoveryForm
     */
    public RecoveryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recovery_container = new javax.swing.JPanel();
        recovery_headerContainer = new javax.swing.JPanel();
        recovery_title = new javax.swing.JLabel();
        recovery_formBody = new javax.swing.JPanel();
        recovery_idLabel = new javax.swing.JLabel();
        recovery_idField = new javax.swing.JTextField();
        recovery_codeLabel = new javax.swing.JLabel();
        recovery_codeField = new javax.swing.JTextField();
        recovery_buttonFooter = new javax.swing.JPanel();
        recovery_backButton = new javax.swing.JPanel();
        recovery_backLabel = new javax.swing.JLabel();
        recovery_resendButton = new javax.swing.JPanel();
        recovery_resendLabel = new javax.swing.JLabel();
        recovery_enterButton = new javax.swing.JPanel();
        recovery_enterLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recovery_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recovery_headerContainer.setBackground(new java.awt.Color(121, 51, 65));
        recovery_headerContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recovery_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recovery_title.setForeground(new java.awt.Color(255, 255, 255));
        recovery_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recovery_title.setText("Temporary Password Reset");
        recovery_headerContainer.add(recovery_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 30));

        recovery_container.add(recovery_headerContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        recovery_formBody.setBackground(new java.awt.Color(132, 71, 71));
        recovery_formBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recovery_idLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recovery_idLabel.setForeground(new java.awt.Color(255, 255, 255));
        recovery_idLabel.setText("ID: ");
        recovery_formBody.add(recovery_idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 20));
        recovery_formBody.add(recovery_idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 30));

        recovery_codeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recovery_codeLabel.setForeground(new java.awt.Color(255, 255, 255));
        recovery_codeLabel.setText("Code:");
        recovery_formBody.add(recovery_codeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 20));
        recovery_formBody.add(recovery_codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 30));

        recovery_container.add(recovery_formBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 120));

        recovery_buttonFooter.setBackground(new java.awt.Color(183, 71, 52));
        recovery_buttonFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recovery_backButton.setBackground(new java.awt.Color(132, 72, 79));
        recovery_backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        recovery_backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recovery_backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recovery_backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recovery_backButtonMouseExited(evt);
            }
        });
        recovery_backButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recovery_backLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recovery_backLabel.setForeground(new java.awt.Color(255, 255, 255));
        recovery_backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recovery_backLabel.setText("Back");
        recovery_backButton.add(recovery_backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        recovery_buttonFooter.add(recovery_backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        recovery_resendButton.setBackground(new java.awt.Color(132, 72, 79));
        recovery_resendButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        recovery_resendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recovery_resendButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recovery_resendButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recovery_resendButtonMouseExited(evt);
            }
        });
        recovery_resendButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recovery_resendLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recovery_resendLabel.setForeground(new java.awt.Color(255, 255, 255));
        recovery_resendLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recovery_resendLabel.setText("Resend Code");
        recovery_resendButton.add(recovery_resendLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        recovery_buttonFooter.add(recovery_resendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, 30));

        recovery_enterButton.setBackground(new java.awt.Color(132, 72, 79));
        recovery_enterButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        recovery_enterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recovery_enterButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recovery_enterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recovery_enterButtonMouseExited(evt);
            }
        });
        recovery_enterButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recovery_enterLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recovery_enterLabel.setForeground(new java.awt.Color(255, 255, 255));
        recovery_enterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recovery_enterLabel.setText("Enter Code");
        recovery_enterButton.add(recovery_enterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        recovery_buttonFooter.add(recovery_enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 30));

        recovery_container.add(recovery_buttonFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recovery_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recovery_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recovery_backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_backButtonMouseEntered
        recovery_backButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_recovery_backButtonMouseEntered

    private void recovery_backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_backButtonMouseExited
        recovery_backButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_recovery_backButtonMouseExited

    private void recovery_enterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_enterButtonMouseEntered
        recovery_enterButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_recovery_enterButtonMouseEntered

    private void recovery_enterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_enterButtonMouseExited
        recovery_enterButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_recovery_enterButtonMouseExited

    private void recovery_resendButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_resendButtonMouseEntered
        recovery_resendButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_recovery_resendButtonMouseEntered

    private void recovery_resendButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_resendButtonMouseExited
        recovery_resendButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_recovery_resendButtonMouseExited

    private void recovery_backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_backButtonMouseClicked
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_recovery_backButtonMouseClicked

    private void recovery_enterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_enterButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_recovery_enterButtonMouseClicked

    private void recovery_resendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recovery_resendButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_recovery_resendButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoveryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoveryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel recovery_backButton;
    private javax.swing.JLabel recovery_backLabel;
    private javax.swing.JPanel recovery_buttonFooter;
    private javax.swing.JTextField recovery_codeField;
    private javax.swing.JLabel recovery_codeLabel;
    private javax.swing.JPanel recovery_container;
    private javax.swing.JPanel recovery_enterButton;
    private javax.swing.JLabel recovery_enterLabel;
    private javax.swing.JPanel recovery_formBody;
    private javax.swing.JPanel recovery_headerContainer;
    private javax.swing.JTextField recovery_idField;
    private javax.swing.JLabel recovery_idLabel;
    private javax.swing.JPanel recovery_resendButton;
    private javax.swing.JLabel recovery_resendLabel;
    private javax.swing.JLabel recovery_title;
    // End of variables declaration//GEN-END:variables
}
