package authentication;

import config.dbConnector;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public RegisterForm() {
        initComponents();
    }
    
    public static String email, username;

    public boolean duplicateCheck(){
        dbConnector dbc = new dbConnector();
        try{
            String query = "SELECT * FROM dashboard_database WHERE member_name " +register_nameField.getText() 
                    + " AND member_password " +register_emailField.getText() + "";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                email = resultSet.getString("member_email");
                if(email.equals(register_emailField.getText())){
                    JOptionPane.showMessageDialog(null, "Email is already used!");
                    register_emailField.setText("");
                }
                username = resultSet.getString("member_name");
                if(email.equals(register_emailField.getText())){
                    JOptionPane.showMessageDialog(null, "Username is already used!");
                    register_nameField.setText(""); 
                }
                return true;
            }
            else{
                return false;
            }
        }
        catch(SQLException ex){
            System.out.println("" +ex);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerContainer = new javax.swing.JPanel();
        register_imageContainer = new javax.swing.JPanel();
        register_formContainer = new javax.swing.JPanel();
        register_nameLabel = new javax.swing.JLabel();
        register_nameField = new javax.swing.JTextField();
        register_passwordLabel = new javax.swing.JLabel();
        register_passwordField = new javax.swing.JPasswordField();
        register_typeLabel = new javax.swing.JLabel();
        register_typeBox = new javax.swing.JComboBox<>();
        register_emailLabel = new javax.swing.JLabel();
        register_emailField = new javax.swing.JTextField();
        register_contactLabel = new javax.swing.JLabel();
        register_confirmLabel = new javax.swing.JLabel();
        register_contactField = new javax.swing.JTextField();
        register_cancelButton = new javax.swing.JPanel();
        register_cancelLabel = new javax.swing.JLabel();
        register_registerButton = new javax.swing.JPanel();
        register_registerLabel = new javax.swing.JLabel();
        register_confirmField = new javax.swing.JPasswordField();
        register_headerContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        registerContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_imageContainer.setBackground(new java.awt.Color(132, 71, 71));
        register_imageContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        registerContainer.add(register_imageContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 340));

        register_formContainer.setBackground(new java.awt.Color(183, 71, 52));
        register_formContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register_nameLabel.setText("Name:");
        register_formContainer.add(register_nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        register_nameField.setBackground(new java.awt.Color(192, 132, 139));
        register_nameField.setForeground(new java.awt.Color(255, 255, 255));
        register_formContainer.add(register_nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        register_passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_passwordLabel.setText("Password:");
        register_formContainer.add(register_passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        register_passwordField.setBackground(new java.awt.Color(192, 132, 139));
        register_passwordField.setForeground(new java.awt.Color(255, 255, 255));
        register_formContainer.add(register_passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 30));

        register_typeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_typeLabel.setText("User Type:");
        register_formContainer.add(register_typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        register_typeBox.setBackground(new java.awt.Color(192, 132, 139));
        register_typeBox.setForeground(new java.awt.Color(255, 255, 255));
        register_typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        register_formContainer.add(register_typeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 30));

        register_emailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_emailLabel.setText("Email:");
        register_formContainer.add(register_emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        register_emailField.setBackground(new java.awt.Color(192, 132, 139));
        register_emailField.setForeground(new java.awt.Color(255, 255, 255));
        register_formContainer.add(register_emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, 30));

        register_contactLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_contactLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_contactLabel.setText("Contact Number:");
        register_formContainer.add(register_contactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        register_confirmLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_confirmLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_confirmLabel.setText("Confirm Password:");
        register_formContainer.add(register_confirmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        register_contactField.setBackground(new java.awt.Color(192, 132, 139));
        register_contactField.setForeground(new java.awt.Color(255, 255, 255));
        register_formContainer.add(register_contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 30));

        register_cancelButton.setBackground(new java.awt.Color(132, 72, 79));
        register_cancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        register_cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_cancelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_cancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_cancelButtonMouseExited(evt);
            }
        });
        register_cancelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_cancelLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_cancelLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register_cancelLabel.setText("Cancel");
        register_cancelButton.add(register_cancelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        register_formContainer.add(register_cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 20));

        register_registerButton.setBackground(new java.awt.Color(132, 72, 79));
        register_registerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        register_registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_registerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_registerButtonMouseExited(evt);
            }
        });
        register_registerButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_registerLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register_registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        register_registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register_registerLabel.setText("Register");
        register_registerButton.add(register_registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        register_formContainer.add(register_registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 20));

        register_confirmField.setBackground(new java.awt.Color(192, 132, 139));
        register_confirmField.setForeground(new java.awt.Color(255, 255, 255));
        register_formContainer.add(register_confirmField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 30));

        registerContainer.add(register_formContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 190, 340));

        register_headerContainer.setBackground(new java.awt.Color(121, 51, 65));
        register_headerContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");
        register_headerContainer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 60, 30));

        registerContainer.add(register_headerContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_cancelButtonMouseClicked
        LoginForm login = new LoginForm();
        
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_register_cancelButtonMouseClicked

    private void register_registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_registerButtonMouseClicked
      
        
        if(register_nameField.getText().isEmpty() && register_passwordField.getPassword().length == 0 
                && register_emailField.getText().isEmpty() && register_contactField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }
        else if(register_passwordField.getPassword().length < 8){
            JOptionPane.showMessageDialog(null, "Password character should be 8 and above.");
        }
        else if(duplicateCheck()){
            System.out.println("Duplicate exists");
        }
        else{
            
            dbConnector dbc = new dbConnector();
            
            try{
                String pass = passwordHasher.hashPassword(register_passwordField.getText());
               
       
                
                if(dbc.insertData("INSERT INTO dashboard_members (member_name, member_password, member_position, member_email, member_contact, member_status) VALUES ('" + register_nameField.getText() + "', '" + pass + "', '" + register_typeBox.getSelectedItem() + "', '" + register_emailField.getText() + "', '" + register_contactField.getText() + "', 'Pending')")){
                    JOptionPane.showMessageDialog(null, "Inserted Successfully!");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Connection Error!");
                }
            }catch(NoSuchAlgorithmException ex){
                System.out.println(""+ex);
            }
        }
    }//GEN-LAST:event_register_registerButtonMouseClicked

    private void register_cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_cancelButtonMouseEntered
        register_cancelButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_register_cancelButtonMouseEntered

    private void register_cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_cancelButtonMouseExited
        register_cancelButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_register_cancelButtonMouseExited

    private void register_registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_registerButtonMouseEntered
        register_registerButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_register_registerButtonMouseEntered

    private void register_registerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_registerButtonMouseExited
        register_registerButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_register_registerButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel registerContainer;
    private javax.swing.JPanel register_cancelButton;
    private javax.swing.JLabel register_cancelLabel;
    private javax.swing.JPasswordField register_confirmField;
    private javax.swing.JLabel register_confirmLabel;
    private javax.swing.JTextField register_contactField;
    private javax.swing.JLabel register_contactLabel;
    private javax.swing.JTextField register_emailField;
    private javax.swing.JLabel register_emailLabel;
    private javax.swing.JPanel register_formContainer;
    private javax.swing.JPanel register_headerContainer;
    private javax.swing.JPanel register_imageContainer;
    private javax.swing.JTextField register_nameField;
    private javax.swing.JLabel register_nameLabel;
    private javax.swing.JPasswordField register_passwordField;
    private javax.swing.JLabel register_passwordLabel;
    private javax.swing.JPanel register_registerButton;
    private javax.swing.JLabel register_registerLabel;
    private javax.swing.JComboBox<String> register_typeBox;
    private javax.swing.JLabel register_typeLabel;
    // End of variables declaration//GEN-END:variables
}
