package page.admin;

import config.dbConnector;
import java.awt.Color;
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class DashboardCreateProduct extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public DashboardCreateProduct() {
        initComponents();
    }
    
    public static String productname;
    public String destination = "", oldpath, path;

    public boolean duplicateCheck(){
        dbConnector dbc = new dbConnector();
        try{
            String query = "SELECT * FROM dashboard_product WHERE product_name " +createproduct_nameField.getText()+ "";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                productname = resultSet.getString("product_name");
                if(productname.equals(createproduct_typeField.getText())){
                    JOptionPane.showMessageDialog(null, "Product's name is already used!");
                    createproduct_typeField.setText(""); 
                }
                return true;
            }
            else{
                return false;
            }
        }
        catch(SQLException ex){
            System.out.println("" +ex);
            return false;
        }
    }
    
    public boolean updateCheck(){
        dbConnector dbc = new dbConnector();
        try{
            String query = "SELECT * FROM dashboard_product WHERE member_name " +createproduct_typeField.getText() 
                    +" AND member_id != "+ createproduct_idField.getText();
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                if(productname.equals(createproduct_typeField.getText())){
                    JOptionPane.showMessageDialog(null, "Product's name is already used!");
                    createproduct_typeField.setText(""); 
                }
                return true;
            }
            else{
                return false;
            }
        }
        catch(SQLException ex){
            System.out.println("" +ex);
            return false;
        }
    }
    DashboardMembers members = new DashboardMembers();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerContainer = new javax.swing.JPanel();
        create_formContainer = new javax.swing.JPanel();
        create_nameLabel = new javax.swing.JLabel();
        createproduct_typeField = new javax.swing.JTextField();
        create_passwordLabel = new javax.swing.JLabel();
        create_typeLabel = new javax.swing.JLabel();
        create_cancelButton = new javax.swing.JPanel();
        create_cancelLabel = new javax.swing.JLabel();
        create_addButton = new javax.swing.JPanel();
        create_addLabel = new javax.swing.JLabel();
        create_updateButton = new javax.swing.JPanel();
        create_cancelLabel1 = new javax.swing.JLabel();
        create_deleteButton = new javax.swing.JPanel();
        create_deleteLabel = new javax.swing.JLabel();
        create_clearButton = new javax.swing.JPanel();
        create_clearLabel = new javax.swing.JLabel();
        create_refreshButton = new javax.swing.JPanel();
        create_refreshLabel = new javax.swing.JLabel();
        createproduct_idField = new javax.swing.JTextField();
        create_idLabel = new javax.swing.JLabel();
        createproduct_nameField = new javax.swing.JTextField();
        createproduct_statusField = new javax.swing.JTextField();
        create_headerContainer = new javax.swing.JPanel();
        create_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        registerContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_formContainer.setBackground(new java.awt.Color(183, 71, 52));
        create_formContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_nameLabel.setText("Name:");
        create_formContainer.add(create_nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        createproduct_typeField.setBackground(new java.awt.Color(192, 132, 139));
        createproduct_typeField.setForeground(new java.awt.Color(255, 255, 255));
        create_formContainer.add(createproduct_typeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 30));

        create_passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_passwordLabel.setText("Type:");
        create_formContainer.add(create_passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        create_typeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_typeLabel.setText("Status: ");
        create_formContainer.add(create_typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        create_cancelButton.setBackground(new java.awt.Color(132, 72, 79));
        create_cancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        create_cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_cancelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_cancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_cancelButtonMouseExited(evt);
            }
        });
        create_cancelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_cancelLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_cancelLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_cancelLabel.setText("Cancel");
        create_cancelButton.add(create_cancelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        create_formContainer.add(create_cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, 20));

        create_addButton.setBackground(new java.awt.Color(132, 72, 79));
        create_addButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        create_addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_addButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_addButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_addButtonMouseExited(evt);
            }
        });
        create_addButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_addLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_addLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_addLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_addLabel.setText("Add");
        create_addButton.add(create_addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        create_formContainer.add(create_addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 20));

        create_updateButton.setBackground(new java.awt.Color(132, 72, 79));
        create_updateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        create_updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_updateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_updateButtonMouseExited(evt);
            }
        });
        create_updateButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_cancelLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_cancelLabel1.setForeground(new java.awt.Color(255, 255, 255));
        create_cancelLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_cancelLabel1.setText("Update");
        create_updateButton.add(create_cancelLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        create_formContainer.add(create_updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, 20));

        create_deleteButton.setBackground(new java.awt.Color(132, 72, 79));
        create_deleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        create_deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_deleteButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_deleteButtonMouseExited(evt);
            }
        });
        create_deleteButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_deleteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_deleteLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_deleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_deleteLabel.setText("Delete");
        create_deleteButton.add(create_deleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        create_formContainer.add(create_deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 80, 20));

        create_clearButton.setBackground(new java.awt.Color(132, 72, 79));
        create_clearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        create_clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_clearButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_clearButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_clearButtonMouseExited(evt);
            }
        });
        create_clearButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_clearLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_clearLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_clearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_clearLabel.setText("Clear");
        create_clearButton.add(create_clearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        create_formContainer.add(create_clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 20));

        create_refreshButton.setBackground(new java.awt.Color(132, 72, 79));
        create_refreshButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        create_refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_refreshButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_refreshButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_refreshButtonMouseExited(evt);
            }
        });
        create_refreshButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_refreshLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_refreshLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_refreshLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_refreshLabel.setText("Refresh");
        create_refreshButton.add(create_refreshLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 20));

        create_formContainer.add(create_refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 20));

        createproduct_idField.setEditable(false);
        createproduct_idField.setBackground(new java.awt.Color(192, 132, 139));
        createproduct_idField.setForeground(new java.awt.Color(255, 255, 255));
        create_formContainer.add(createproduct_idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        create_idLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_idLabel.setForeground(new java.awt.Color(255, 255, 255));
        create_idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_idLabel.setText("ID: ");
        create_formContainer.add(create_idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        createproduct_nameField.setBackground(new java.awt.Color(192, 132, 139));
        createproduct_nameField.setForeground(new java.awt.Color(255, 255, 255));
        create_formContainer.add(createproduct_nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 30));

        createproduct_statusField.setBackground(new java.awt.Color(192, 132, 139));
        createproduct_statusField.setForeground(new java.awt.Color(255, 255, 255));
        create_formContainer.add(createproduct_statusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 30));

        registerContainer.add(create_formContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 300));

        create_headerContainer.setBackground(new java.awt.Color(121, 51, 65));
        create_headerContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create_title.setForeground(new java.awt.Color(255, 255, 255));
        create_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_title.setText("Create Product");
        create_headerContainer.add(create_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 30));

        registerContainer.add(create_headerContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_cancelButtonMouseClicked
        members.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_create_cancelButtonMouseClicked

    private void create_addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_addButtonMouseClicked
        if(createproduct_nameField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }
        else if(duplicateCheck()){
            System.out.println("Duplicate exists");
        }
        else{
            dbConnector dbc = new dbConnector();
            if(dbc.insertData("INSERT INTO dashboard_products (product_name, product_type, product_status) VALUES ('" + createproduct_nameField.getText() + "', '" + createproduct_typeField.getText() + "', '" + createproduct_statusField.getText() + ")")){
                JOptionPane.showMessageDialog(null, "Registered Successfully!");
                
                members.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Connection Error!");
            }
        }
    }//GEN-LAST:event_create_addButtonMouseClicked

    private void create_cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_cancelButtonMouseEntered
        create_cancelButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_create_cancelButtonMouseEntered

    private void create_cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_cancelButtonMouseExited
        create_cancelButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_create_cancelButtonMouseExited

    private void create_addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_addButtonMouseEntered
        create_addButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_create_addButtonMouseEntered

    private void create_addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_addButtonMouseExited
        create_addButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_create_addButtonMouseExited

    private void create_deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_deleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_create_deleteButtonMouseClicked

    private void create_deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_deleteButtonMouseEntered
        create_deleteButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_create_deleteButtonMouseEntered

    private void create_deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_deleteButtonMouseExited
        create_deleteButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_create_deleteButtonMouseExited

    private void create_updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_updateButtonMouseClicked
        if(createproduct_typeField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }
        else if(updateCheck()){
            System.out.println("Duplicate exists");
        }
        else{
            dbConnector dbc = new dbConnector();
            dbc.updateData("UPDATE dashboard_products SET product_name = " +createproduct_nameField.getText()+ ", product_type = " 
                +createproduct_typeField.getText()+ ", product_status = " +createproduct_typeField.getText()
                    + " WHERE product_id" +createproduct_idField.getText());
        
            JOptionPane.showMessageDialog(null, "Registered Successfully!");
                members.setVisible(true);
                this.dispose();
        }
    }//GEN-LAST:event_create_updateButtonMouseClicked

    private void create_updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_updateButtonMouseEntered
        create_updateButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_create_updateButtonMouseEntered

    private void create_updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_updateButtonMouseExited
        create_updateButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_create_updateButtonMouseExited

    private void create_clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_clearButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_create_clearButtonMouseClicked

    private void create_clearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_clearButtonMouseEntered
        create_clearButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_create_clearButtonMouseEntered

    private void create_clearButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_clearButtonMouseExited
        create_clearButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_create_clearButtonMouseExited

    private void create_refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_refreshButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_create_refreshButtonMouseClicked

    private void create_refreshButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_refreshButtonMouseEntered
        create_refreshButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_create_refreshButtonMouseEntered

    private void create_refreshButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_refreshButtonMouseExited
        create_refreshButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_create_refreshButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardCreateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel create_addButton;
    private javax.swing.JLabel create_addLabel;
    private javax.swing.JPanel create_cancelButton;
    private javax.swing.JLabel create_cancelLabel;
    private javax.swing.JLabel create_cancelLabel1;
    private javax.swing.JPanel create_clearButton;
    private javax.swing.JLabel create_clearLabel;
    private javax.swing.JPanel create_deleteButton;
    private javax.swing.JLabel create_deleteLabel;
    private javax.swing.JPanel create_formContainer;
    private javax.swing.JPanel create_headerContainer;
    private javax.swing.JLabel create_idLabel;
    private javax.swing.JLabel create_nameLabel;
    private javax.swing.JLabel create_passwordLabel;
    private javax.swing.JPanel create_refreshButton;
    private javax.swing.JLabel create_refreshLabel;
    private javax.swing.JLabel create_title;
    private javax.swing.JLabel create_typeLabel;
    public javax.swing.JPanel create_updateButton;
    public javax.swing.JTextField createproduct_idField;
    public javax.swing.JTextField createproduct_nameField;
    public javax.swing.JTextField createproduct_statusField;
    public javax.swing.JTextField createproduct_typeField;
    private javax.swing.JPanel registerContainer;
    // End of variables declaration//GEN-END:variables
}
