package adminpage;

import authentication.RegisterForm;
import config.dbConnector;
import java.awt.Color;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class DashboardMembers extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashboardMembers() {
        initComponents();
        displayData();
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT member_id, member_name, member_position, member_email, member_contact, member_status"
                    + " FROM dashboard_members");
            members_membersTable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }
        catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard_members = new javax.swing.JPanel();
        members_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        members_container = new javax.swing.JPanel();
        members_tableScroller = new javax.swing.JScrollPane();
        members_membersTable = new javax.swing.JTable();
        members_backButton = new javax.swing.JPanel();
        members_backLabel = new javax.swing.JLabel();
        members_filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        members_createButton = new javax.swing.JPanel();
        members_createLabel = new javax.swing.JLabel();
        members_readButton = new javax.swing.JPanel();
        members_readLabel = new javax.swing.JLabel();
        members_updateButton = new javax.swing.JPanel();
        members_updateLabel = new javax.swing.JLabel();
        members_deleteButton = new javax.swing.JPanel();
        members_deleteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard_members.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_header.setBackground(new java.awt.Color(121, 51, 65));
        members_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Members");
        members_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 170, 10));

        dashboard_members.add(members_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 30));

        members_container.setBackground(new java.awt.Color(183, 71, 52));
        members_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_tableScroller.setBackground(new java.awt.Color(192, 132, 139));
        members_tableScroller.setForeground(new java.awt.Color(255, 255, 255));

        members_membersTable.setBackground(new java.awt.Color(132, 72, 79));
        members_membersTable.setForeground(new java.awt.Color(255, 255, 255));
        members_membersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Position", "Email", "Contact Number", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        members_tableScroller.setViewportView(members_membersTable);

        members_container.add(members_tableScroller, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 300));

        members_backButton.setBackground(new java.awt.Color(132, 72, 79));
        members_backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        members_backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                members_backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                members_backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                members_backButtonMouseExited(evt);
            }
        });
        members_backButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_backLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        members_backLabel.setForeground(new java.awt.Color(255, 255, 255));
        members_backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members_backLabel.setText("Back");
        members_backButton.add(members_backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        members_container.add(members_backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 50));
        members_container.add(members_filler, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -30, 10, 410));

        members_createButton.setBackground(new java.awt.Color(132, 72, 79));
        members_createButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        members_createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                members_createButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                members_createButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                members_createButtonMouseExited(evt);
            }
        });
        members_createButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_createLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        members_createLabel.setForeground(new java.awt.Color(255, 255, 255));
        members_createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members_createLabel.setText("Create");
        members_createButton.add(members_createLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        members_container.add(members_createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, 50));

        members_readButton.setBackground(new java.awt.Color(132, 72, 79));
        members_readButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        members_readButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                members_readButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                members_readButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                members_readButtonMouseExited(evt);
            }
        });
        members_readButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_readLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        members_readLabel.setForeground(new java.awt.Color(255, 255, 255));
        members_readLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members_readLabel.setText("Read");
        members_readButton.add(members_readLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        members_container.add(members_readButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 130, 50));

        members_updateButton.setBackground(new java.awt.Color(132, 72, 79));
        members_updateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        members_updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                members_updateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                members_updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                members_updateButtonMouseExited(evt);
            }
        });
        members_updateButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_updateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        members_updateLabel.setForeground(new java.awt.Color(255, 255, 255));
        members_updateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members_updateLabel.setText("Update");
        members_updateButton.add(members_updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        members_container.add(members_updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 130, 50));

        members_deleteButton.setBackground(new java.awt.Color(132, 72, 79));
        members_deleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 132, 139)));
        members_deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                members_deleteButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                members_deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                members_deleteButtonMouseExited(evt);
            }
        });
        members_deleteButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        members_deleteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        members_deleteLabel.setForeground(new java.awt.Color(255, 255, 255));
        members_deleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        members_deleteLabel.setText("Delete");
        members_deleteButton.add(members_deleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        members_container.add(members_deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 130, 50));

        dashboard_members.add(members_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 710, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dashboard_members, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dashboard_members, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void members_backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_backButtonMouseExited
        members_backButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_members_backButtonMouseExited

    private void members_backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_backButtonMouseEntered
        members_backButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_members_backButtonMouseEntered

    private void members_backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_backButtonMouseClicked
        DashboardAdmin adminPage = new DashboardAdmin();
        adminPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_members_backButtonMouseClicked

    private void members_createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_createButtonMouseClicked
        
    }//GEN-LAST:event_members_createButtonMouseClicked

    private void members_createButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_createButtonMouseEntered
        members_createButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_members_createButtonMouseEntered

    private void members_createButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_createButtonMouseExited
        members_createButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_members_createButtonMouseExited

    private void members_readButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_readButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_members_readButtonMouseClicked

    private void members_readButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_readButtonMouseEntered
        members_readButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_members_readButtonMouseEntered

    private void members_readButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_readButtonMouseExited
        members_readButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_members_readButtonMouseExited

    private void members_updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_updateButtonMouseClicked
        int rowIndex = members_membersTable.getSelectedRow();
        
        TableModel tbl = members_membersTable.getModel();
        
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select an item!");
        }
        else{
            
        }
    }//GEN-LAST:event_members_updateButtonMouseClicked

    private void members_updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_updateButtonMouseEntered
        members_updateButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_members_updateButtonMouseEntered

    private void members_updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_updateButtonMouseExited
        members_updateButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_members_updateButtonMouseExited

    private void members_deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_deleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_members_deleteButtonMouseClicked

    private void members_deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_deleteButtonMouseEntered
        members_deleteButton.setBackground(new Color(192, 132, 139));
    }//GEN-LAST:event_members_deleteButtonMouseEntered

    private void members_deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_members_deleteButtonMouseExited
        members_deleteButton.setBackground(new Color(132, 72, 79));
    }//GEN-LAST:event_members_deleteButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardMembers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboard_members;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel members_backButton;
    private javax.swing.JLabel members_backLabel;
    private javax.swing.JPanel members_container;
    private javax.swing.JPanel members_createButton;
    private javax.swing.JLabel members_createLabel;
    private javax.swing.JPanel members_deleteButton;
    private javax.swing.JLabel members_deleteLabel;
    private javax.swing.Box.Filler members_filler;
    private javax.swing.JPanel members_header;
    private javax.swing.JTable members_membersTable;
    private javax.swing.JPanel members_readButton;
    private javax.swing.JLabel members_readLabel;
    private javax.swing.JScrollPane members_tableScroller;
    private javax.swing.JPanel members_updateButton;
    private javax.swing.JLabel members_updateLabel;
    // End of variables declaration//GEN-END:variables
}
